WebApplication3/Models/Speaker.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CURDOperationWithImageUploadCore5_Demo.Models
{
    public class Speaker
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Name")]
        public string SpeakerName { get; set; }

        

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Date")]
        public DateTime SpeakingDate { get; set; }



        [Required]
        [Display(Name = "Image")]
        public string ProfilePicture { get; set; }
    }
}

WebApplication3/ViewModels/SpeakerViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CURDOperationWithImageUploadCore5_Demo.ViewModels
{
    public class SpeakerViewModel : EditImageViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string SpeakerName { get; set; }



        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Date")]
        public DateTime SpeakingDate { get; set; }


    }
}

WebApplication3/Controllers/SpeakersController.cs
using CURDOperationWithImageUploadCore5_Demo.Data;
using CURDOperationWithImageUploadCore5_Demo.Models;
using CURDOperationWithImageUploadCore5_Demo.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CURDOperationWithImageUploadCore5_Demo.Controllers
{
    public class SpeakersController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IWebHostEnvironment webHostEnvironment;
        public SpeakersController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            db = context;
            webHostEnvironment = hostEnvironment;
        }

        public async Task<IActionResult> Index(string searchBy, string search)
        {
            if (searchBy == "Date")
            {
                return View(await db.Speakers.Where(x => x.ProfilePicture == search || search == null).ToListAsync());
            }
            else
            {
                return View(await db.Speakers.Where(x => x.SpeakerName.StartsWith(search) || search == null).ToListAsync());
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speaker = await db.Speakers
                .FirstOrDefaultAsync(m => m.Id == id);

            var speakerViewModel = new SpeakerViewModel()
            {
                Id = speaker.Id,
                SpeakerName = speaker.SpeakerName,

                SpeakingDate = speaker.SpeakingDate,
                ExistingImage = speaker.ProfilePicture
            };

            if (speaker == null)
            {
                return NotFound();
            }

            return View(speaker);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpeakerViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = ProcessUploadedFile(model);
                Speaker speaker = new Speaker
                {
                    SpeakerName = model.SpeakerName,

                    SpeakingDate = model.SpeakingDate,

                    ProfilePicture = uniqueFileName
                };

                db.Add(speaker);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speaker = await db.Speakers.FindAsync(id);
            var speakerViewModel = new SpeakerViewModel()
            {
                Id = speaker.Id,
                SpeakerName = speaker.SpeakerName,

                SpeakingDate = speaker.SpeakingDate,

                ExistingImage = speaker.ProfilePicture
            };

            if (speaker == null)
            {
                return NotFound();
            }
            return View(speakerViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SpeakerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var speaker = await db.Speakers.FindAsync(model.Id);
                speaker.SpeakerName = model.SpeakerName;

                speaker.SpeakingDate = model.SpeakingDate;


                if (model.SpeakerPicture != null)
                {
                    if (model.ExistingImage != null)
                    {
                        string filePath = Path.Combine(webHostEnvironment.WebRootPath, "Uploads", model.ExistingImage);
                        System.IO.File.Delete(filePath);
                    }

                    speaker.ProfilePicture = ProcessUploadedFile(model);
                }
                db.Update(speaker);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speaker = await db.Speakers
                .FirstOrDefaultAsync(m => m.Id == id);

            var speakerViewModel = new SpeakerViewModel()
            {
                Id = speaker.Id,
                SpeakerName = speaker.SpeakerName,

                SpeakingDate = speaker.SpeakingDate,

                ExistingImage = speaker.ProfilePicture
            };
            if (speaker == null)
            {
                return NotFound();
            }

            return View(speakerViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var speaker = await db.Speakers.FindAsync(id);
            var CurrentImage = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", speaker.ProfilePicture);
            db.Speakers.Remove(speaker);
            if (await db.SaveChangesAsync() > 0)
            {
                if (System.IO.File.Exists(CurrentImage))
                {
                    System.IO.File.Delete(CurrentImage);
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private bool SpeakerExists(int id)
        {
            return db.Speakers.Any(e => e.Id == id);
        }

        private string ProcessUploadedFile(SpeakerViewModel model)
        {
            string uniqueFileName = null;

            if (model.SpeakerPicture != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "Uploads");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.SpeakerPicture.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.SpeakerPicture.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

WebApplication3/Views/Speakers/Create.cshtml
@model CURDOperationWithImageUploadCore5_Demo.ViewModels.SpeakerViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Speaker</h4>
<hr />
<div class="card">
    <div class="card-header">
        <h3 class="text-uppercase">New Item</h3>
    </div>
    <div class="card-body">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="SpeakerName" class="control-label"></label>
                        <input asp-for="SpeakerName" class="form-control" />
                        <span asp-validation-for="SpeakerName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="SpeakingDate" class="control-label"></label>
                        <input asp-for="SpeakingDate" class="form-control" />
                        <span asp-validation-for="SpeakingDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="SpeakerPicture" class="control-label"></label>
                        <div class="custom-file">
                            <input asp-for="SpeakerPicture" class="custom-file-input" />
                            <label class="custom-file-label" for="customFile">Choose File</label>
                        </div>
                    </div>
                </div>
                <span asp-validation-for="SpeakerPicture" class="text-danger"></span>
            </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
<script>
    $(".custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script> 
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication3/Views/Speakers/Delete.cshtml
@model CURDOperationWithImageUploadCore5_Demo.ViewModels.SpeakerViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpeakerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpeakerName)
        </dd>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpeakingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpeakingDate)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpeakerPicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpeakerPicture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication3/Views/Speakers/Details.cshtml
@model CURDOperationWithImageUploadCore5_Demo.Models.Speaker

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Speaker</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpeakerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpeakerName)
        </dd>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpeakingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpeakingDate)
        </dd>

        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication3/Views/Speakers/Edit.cshtml
@model CURDOperationWithImageUploadCore5_Demo.ViewModels.SpeakerViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Speaker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SpeakerName" class="control-label"></label>
                <input asp-for="SpeakerName" class="form-control" />
                <span asp-validation-for="SpeakerName" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="SpeakingDate" class="control-label"></label>
                <input asp-for="SpeakingDate" class="form-control" />
                <span asp-validation-for="SpeakingDate" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="SpeakerPicture" class="control-label"></label>
                <div class="custom-file">
                <input asp-for="SpeakerPicture" class="custom-file-input" />
                    <label class="custom-file-label" for="customFile">Choose File</label>
                </div>
                <span asp-validation-for="SpeakerPicture" class="text-danger"></span>
                <img src="~/Uploads/@Model.ExistingImage" class="img-thumbnail" height="80" width="80" asp-append-version="true" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script>
    $(".custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication3/Views/Speakers/Index.cshtml
@model IEnumerable<CURDOperationWithImageUploadCore5_Demo.Models.Speaker>
@inject SignInManager<IdentityUser> SignInManager
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
@if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin") || User.IsInRole("Staff"))
{
<p>

    <a asp-action="Create" class="btn btn-primary rounded-0"><i class="fa fa-plus-circle"></i> Add New</a>
</p>
}

<p>
    @using (Html.BeginForm("Index", "Speakers", FormMethod.Get))
    {
        @*<b>Search By:</b> @Html.RadioButton("searchBy", "name", true) <p>Name</p>
            @Html.RadioButton("searchBy", "picture") <p>Date</p>*@
        @Html.TextBox("search") @*<input type="submit" value="Search" />*@
        <button type="submit" class="btn btn-dark">Search</button>
    }


</p>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProfilePicture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpeakerName)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.SpeakingDate)
            </th>

        </tr>
    </thead>
    <tbody>

        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4">No rows match search criteria</td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id">
                            <img src="~/Uploads/@item.ProfilePicture" class="img-thumbnail" height="100" width="100" asp-append-version="true" />
                        </a>
                    </td>
                    <td>@item.SpeakerName</td>

                    <td>@item.SpeakingDate</td>

                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin") || User.IsInRole("Staff"))
                    {
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-info rounded-0"><i class="fa fa-pencil-alt"></i></a>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger rounded-0"><i class="fa fa-trash-alt"></i></a>
                        </td>
                    }
                </tr>

            }
        }
        </tbody>
</table>